#!/usr/bin/env bun
import { $ } from "bun"
import pkg from "../package.json"
import { Script } from "@altimate/cli-script"
import { fileURLToPath } from "url"

const dir = fileURLToPath(new URL("..", import.meta.url))
process.chdir(dir)

const binaries: Record<string, string> = {}
for (const filepath of new Bun.Glob("@altimateai/*/package.json").scanSync({ cwd: "./dist" })) {
  const pkg = await Bun.file(`./dist/${filepath}`).json()
  binaries[pkg.name] = pkg.version
}
console.log("binaries", binaries)
const version = Object.values(binaries)[0]

await $`mkdir -p ./dist/${pkg.name}`
await $`cp -r ./bin ./dist/${pkg.name}/bin`
await $`cp ./script/postinstall.mjs ./dist/${pkg.name}/postinstall.mjs`
await Bun.file(`./dist/${pkg.name}/LICENSE`).write(await Bun.file("../../LICENSE").text())

await Bun.file(`./dist/${pkg.name}/package.json`).write(
  JSON.stringify(
    {
      name: "@altimateai/altimate-code",
      bin: {
        "altimate-code": "./bin/altimate-code",
      },
      scripts: {
        postinstall: "bun ./postinstall.mjs || node ./postinstall.mjs",
      },
      version: version,
      license: pkg.license,
      optionalDependencies: binaries,
    },
    null,
    2,
  ),
)

const tasks = Object.entries(binaries).map(async ([name]) => {
  if (process.platform !== "win32") {
    await $`chmod -R 755 .`.cwd(`./dist/${name}`)
  }
  await $`bun pm pack`.cwd(`./dist/${name}`)
  await $`npm publish *.tgz --access public --tag ${Script.channel}`.cwd(`./dist/${name}`)
})
await Promise.all(tasks)
await $`cd ./dist/${pkg.name} && bun pm pack && npm publish *.tgz --access public --tag ${Script.channel}`

// registries (AUR, Homebrew)
if (!Script.preview) {
  // Calculate SHA values
  const arm64Sha = await $`sha256sum "./dist/altimate-code-linux-arm64.tar.gz" | cut -d' ' -f1`.text().then((x) => x.trim())
  const x64Sha = await $`sha256sum "./dist/altimate-code-linux-x64.tar.gz" | cut -d' ' -f1`.text().then((x) => x.trim())
  const macX64Sha = await $`sha256sum "./dist/altimate-code-darwin-x64.zip" | cut -d' ' -f1`.text().then((x) => x.trim())
  const macArm64Sha = await $`sha256sum "./dist/altimate-code-darwin-arm64.zip" | cut -d' ' -f1`.text().then((x) => x.trim())

  const [pkgver, _subver = ""] = Script.version.split(/(-.*)/, 2)

  // TODO: AUR (Arch User Repository) publishing — skipped for now
  // To enable AUR publishing:
  // 1. Create an AUR account at https://aur.archlinux.org/register
  // 2. Generate an SSH key: ssh-keygen -t ed25519 -C "altimate-aur-ci" -f aur_ed25519 -N ""
  // 3. Add the public key (aur_ed25519.pub) to AUR: My Account > SSH Public Key
  // 4. Register the package on AUR: Submit Request > Package Name: "altimate-code-bin"
  // 5. Add private key as GitHub secret: AUR_SSH_PRIVATE_KEY
  // 6. Uncomment the "Configure SSH for AUR" step in .github/workflows/release.yml
  // 7. Uncomment the AUR block below
  //
  // The PKGBUILD and .SRCINFO are generated in TypeScript (no makepkg/Arch dependency).
  // The flow: clone AUR repo via SSH → write PKGBUILD + .SRCINFO → commit → push.
  // Uses arm64Sha, x64Sha, pkgver, _subver from above.

  // Homebrew formula
  const homebrewFormula = [
    "# typed: false",
    "# frozen_string_literal: true",
    "",
    "# This file was generated by GoReleaser. DO NOT EDIT.",
    "class AltimateCode < Formula",
    `  desc "AI-powered CLI for SQL analysis, dbt integration, and data engineering"`,
    `  homepage "https://github.com/AltimateAI/altimate-code"`,
    `  version "${Script.version.split("-")[0]}"`,
    "",
    `  depends_on "ripgrep"`,
    "",
    "  on_macos do",
    "    if Hardware::CPU.intel?",
    `      url "https://github.com/AltimateAI/altimate-code/releases/download/v${Script.version}/altimate-code-darwin-x64.zip"`,
    `      sha256 "${macX64Sha}"`,
    "",
    "      def install",
    '        bin.install "altimate-code"',
    "      end",
    "    end",
    "    if Hardware::CPU.arm?",
    `      url "https://github.com/AltimateAI/altimate-code/releases/download/v${Script.version}/altimate-code-darwin-arm64.zip"`,
    `      sha256 "${macArm64Sha}"`,
    "",
    "      def install",
    '        bin.install "altimate-code"',
    "      end",
    "    end",
    "  end",
    "",
    "  on_linux do",
    "    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?",
    `      url "https://github.com/AltimateAI/altimate-code/releases/download/v${Script.version}/altimate-code-linux-x64.tar.gz"`,
    `      sha256 "${x64Sha}"`,
    "      def install",
    '        bin.install "altimate-code"',
    "      end",
    "    end",
    "    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?",
    `      url "https://github.com/AltimateAI/altimate-code/releases/download/v${Script.version}/altimate-code-linux-arm64.tar.gz"`,
    `      sha256 "${arm64Sha}"`,
    "      def install",
    '        bin.install "altimate-code"',
    "      end",
    "    end",
    "  end",
    "end",
    "",
    "",
  ].join("\n")

  const token = process.env.GITHUB_TOKEN
  if (!token) {
    console.error("GITHUB_TOKEN is required to update homebrew tap")
    process.exit(1)
  }
  const tapUrl = `https://x-access-token:${token}@github.com/AltimateAI/homebrew-tap.git`
  await $`rm -rf ./dist/homebrew-tap`
  await $`git clone ${tapUrl} ./dist/homebrew-tap`
  await Bun.file("./dist/homebrew-tap/altimate-code.rb").write(homebrewFormula)
  await $`cd ./dist/homebrew-tap && git config user.name "AltimateAI Bot"`
  await $`cd ./dist/homebrew-tap && git config user.email "bot@altimate.ai"`
  await $`cd ./dist/homebrew-tap && git add altimate-code.rb`
  await $`cd ./dist/homebrew-tap && git commit -m "Update to v${Script.version}"`
  await $`cd ./dist/homebrew-tap && git push`
}
